### ISSUE TITLE
[bug] wx.request 中 headers 属性值错误

### ISSUE THREAD

**Issue by Rabbitzzc** [raxjs/universal-api#140]
代码：https://github.com/raxjs/universal-api/blob/master/src/packages/network/request/src/wechat-miniprogram/index.ts#L12

![image](https://user-images.githubusercontent.com/26913511/115247955-d2755c00-a159-11eb-8d66-3a776e1f6ba5.png)

![image](https://user-images.githubusercontent.com/26913511/115247812-b2de3380-a159-11eb-872c-514cf035be6c.png)

不能直接使用 es6 语法，应该改为

```js
header: headers
```

**Comment by SoloJiang** [comment]
可以直接 PR 解决下

**Comment by Rabbitzzc** [comment]
效率高
