### ISSUE TITLE
[Question]@uni/request Web端为什么失败也会触发success

### ISSUE THREAD

**Issue by cielyic** [raxjs/universal-api#182]
背景
```
request({
  url: 'https://alibaba.github.io/rax/',
  method: 'POST',
  data: {
    from: 'Rax',
  },
  dataType: 'json',
  success: (res) => {
    console.log('success', res);
  },
  fail: (res) => {
    console.log('fail', res);
  },
  complete: (res) => {
    console.log('complete', res);
  },
});
```
- 会返回失败

预期：
- 只触发fail和complete

但实际
- 触发success、fail、complete

然后我看源码
https://github.com/raxjs/universal-api/blob/master/src/packages/network/request/src/web/index.ts

![image](https://user-images.githubusercontent.com/51021027/122021888-af34f900-cdf8-11eb-90bb-c3c3dda53faf.png)

这里遇到错误并没有return掉

**Comment by SoloJiang** [comment]
直接来个 PR？

**Comment by cielyic** [comment]
> 直接来个 PR？

不会

**Comment by DOBEEE** [comment]
@uni/request@1.0.8-beta 试下

**Comment by cielyic** [comment]
> @uni/request@1.0.8-beta 试下

有个问题，在微信小程序，是在api调用失败的时候才走fail，正常不管什么status都是走success

**Comment by DOBEEE** [comment]
@uni/request@1.0.9-beta 调整了所有容器的实现都增加对status的判别，可以试下
