### ISSUE TITLE
rax工程  导入 uni/apis 运行报错

### ISSUE THREAD

**Issue by reganan** [raxjs/universal-api#185]
![image](https://user-images.githubusercontent.com/8327090/122172040-f41d6600-ceb2-11eb-97e3-89480da0161a.png)
![image](https://user-images.githubusercontent.com/8327090/122172070-fda6ce00-ceb2-11eb-81fa-99b2133b1851.png)
![image](https://user-images.githubusercontent.com/8327090/122172159-11523480-ceb3-11eb-8cab-789b40bab171.png)
![image](https://user-images.githubusercontent.com/8327090/122172210-1b743300-ceb3-11eb-9ce7-ebe5479e335a.png)

主包es目录下，引入未打包组件’animation‘组件，导致运行报错。
目前个人解决方案，去掉对应限制，编译之后，再替换本地的包。
希望修复下

**Comment by DOBEEE** [comment]
@uni/apis@1.0.15-beta
