### ISSUE TITLE
@uni/clipboard浏览器ios模拟，setClipboard不起作用

### ISSUE THREAD

**Issue by wjw131211** [raxjs/universal-api#187]
setClipboard逻辑是否需完善

**Comment by brightcd** [comment]
可以提供具体的复现场景吗？机型、操作系统版本、浏览器，我在iphone7 ios13.6 safari和微信浏览器内跑demo都是ok的，setClipboard可以正确设置剪切板内容

确保@uni/clipboard是最新版本，针对ios单独处理做过一次升级

**Comment by DOBEEE** [comment]
长时间未响应，暂时关闭
