### ISSUE TITLE
@uni/request

### ISSUE THREAD

**Issue by cielyic** [raxjs/universal-api#200]
背景：
request({}) 设置了headers但没有设置'Content-Type': 'application/json',  Content-Type的默认值为Content-Type: text/plain;charset=UTF-8

希望：
在自定义headers时，没有设置Content-type时默认值也还是'application/json'

**Comment by DOBEEE** [comment]
你好，辛苦反馈下复现的 容器类型

**Comment by cielyic** [comment]
> 你好，辛苦反馈下复现的 容器类型

web

**Comment by DOBEEE** [comment]
已解决
