### ISSUE TITLE
@uni/env能否支持判断isRax吗？

### ISSUE THREAD

**Issue by xmsz** [raxjs/universal-api#205]
背景
- web页面跳转
- rax或者react/vue都是用自己的api进行跳转，因为用@uni/navigate跳转会刷新页面（毕竟直接调用的是history）
- 所以希望可以在env里判断当前环境是不是isRax，这样就能判断使用了

需求
- isRax判断是否是rax环境

**Comment by ChrisCindy** [comment]
@uni/env 是用于判断容器环境，不会判断当前使用框架。

**Comment by xmsz** [comment]
> @uni/env 是用于判断容器环境，不会判断当前使用框架。

好吧 明白了
