### ISSUE TITLE
本地调试：InitialComponent is not a function

### ISSUE THREAD

**Issue by Yahiko7** [raxjs/universal-api#206]
本地调试http://127.0.0.1:3333/
Uncaught (in promise) TypeError: InitialComponent is not a function
![image](https://user-images.githubusercontent.com/15901380/126860229-9040cfd9-25ba-401b-b596-15fff1e03bdc.png)
![image](https://user-images.githubusercontent.com/15901380/126860236-b4bebd20-d7c6-4b95-bdaf-9a4ec97099cb.png)

**Comment by DOBEEE** [comment]
本地调试时，首页路径为 http://127.0.0.1:3333/pages/Home/index，辛苦手动替换下
