### ISSUE TITLE
支付宝小程序已经不推荐使用createCanvasContext

### ISSUE THREAD

**Issue by chenhebing** [raxjs/universal-api#258]
https://opendocs.alipay.com/mini/api/ui-canvas

通过createCanvasContext获取到的ctx无法获取对应的canvas节点，会导致在使用第三方渲染库时无法使用，希望添加获取canvas的通用api

**Comment by DOBEEE** [comment]
已修复发布  @uni/canvas@1.0.8

**Comment by chenhebing** [comment]
邮件已收到，谢谢！
