### ISSUE TITLE
新版本丢失keyboard

### ISSUE THREAD

**Issue by boomlion** [raxjs/universal-api#291]
./node_modules/_@uni_apis@1.1.12@@uni/apis/es/main/web/index.js， 
Module not found: Can't resolve '../../packages/interactive/keyboard/src/web/index' in '/Users/xxxx/Desktop/font-other/recycle-user/node_modules/_@uni_apis@1.1.12@@uni/apis/es/main/web'

**Comment by ChrisCindy** [comment]
已回滚版本，稍后修复

**Comment by boomlion** [comment]
等你消息，nikui
