### ISSUE TITLE
universal-clipboard iOS 无法复制

### ISSUE THREAD

**Issue by javaxiu** [raxjs/universal-api#94]
实测，在任何版本的 iOS ，web 环境下，复制功能是无效的，粘贴板内容会是空的。
review 代码，把这行删掉可以解决问题
https://github.com/raxjs/universal-api/blob/master/packages/clipboard/src/web/index.ts#L11

input 框的插入移除时间很短，肉眼看不到有变化，行高不设置为 0 也不会有影响

**Comment by SoloJiang** [comment]
会存在闪动吧

**Comment by javaxiu** [comment]
如 issue 所提，实测高度为 0 的情况下肉眼并不可见闪动。

**Comment by ChrisCindy** [comment]
@DOBEEE check 一下 @uni/clipboard 是否也存在这个问题

**Comment by brightcd** [comment]
@uni/clipboard 也存在这个问题，并且实测safari删掉高度也不能复制

**Comment by cccRaim** [comment]
这个是ios的限制，解决方案是至少设置1px，可以考虑用绝对定位把相关元素移动到视窗外，如-1000px

**Comment by DOBEEE** [comment]
@uni/clipboard@1.0.5-beta 已修复
